install.packages("naivebayes")
install.packages("ggplot2")
install.packages("e1071")
library(naivebayes)
library(ggplot2)
library(e1071)
salary_train<-read.csv("C:/Users/india/Desktop/data science/assignments/naive bayes/SalaryData_Train.csv")
View(salary_train)
str(salary_train)
salary_train$educationno<-as.factor(salary_train$educationno)
salary_test<-read.csv("C:/Users/india/Desktop/data science/assignments/naive bayes/SalaryData_Test.csv")
View(salary_test)
str(salary_test)
salary_test$educationno<-as.factor(salary_test$educationno)
plot(salary_train$age,salary_train$Salary,type = "h")
plot(salary_train$workclass,salary_train$Salary)
plot(salary_train$education,salary_train$Salary)
plot(salary_train$educationno,salary_train$Salary)
plot(salary_train$maritalstatus,salary_train$Salary)
plot(salary_train$occupation,salary_train$Salary)
plot(salary_train$relationship,salary_train$Salary)
plot(salary_train$race,salary_train$Salary)
plot(salary_train$sex,salary_train$Salary)
plot(salary_train$capitalgain,salary_train$Salary,type = "h")
plot(salary_train$capitalloss,salary_train$Salary,type = "h")
plot(salary_train$hoursperweek,salary_train$Salary,type = "h")
plot(salary_train$native,salary_train$Salary)
boxplot(salary_train$Salary,salary_train$age)
boxplot(salary_train$Salary,salary_train$capitalgain)
boxplot(salary_train$Salary,salary_train$capitalloss)
boxplot(salary_train$Salary,salary_train$hoursperweek)

model<-naiveBayes(salary_train$Salary~.,data = salary_train)
pred<-predict(model,salary_test)
mean(pred==salary_train$Salary)
table(pred)

