install.packages("kernlab")
install.packages("caret")
library(kernlab)
library(caret)
library(ggplot2)
#Train data
salary_train<-read.csv("C:/Users/india/Desktop/data science/assignments/svm/SalaryData_Train.csv")
level_work <- levels(salary_train$workclass)
leveledu <- levels(salary_train$education)
level_mari <- levels(salary_train$maritalstatus)
level_occ <- levels(salary_train$occupation)
level_rel <- levels(salary_train$relationship)
level_race <- levels(salary_train$race)
level_sex <- levels(salary_train$sex)
level_native <- levels(salary_train$native)
level_salary <- levels(salary_train$Salary)
salary_train$workclass <- as.integer(factor(salary_train$workclass,levels =c(level_work),labels=c(1,2,3,4,5,6,7)))
salary_train$education <- as.integer(factor(salary_train$education,levels = c(leveledu),labels = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16))) 
salary_train$maritalstatus <- as.integer(factor(salary_train$maritalstatus,levels = c(level_mari),labels =c(1,2,3,4,5,6,7) ))
salary_train$occupation <- as.integer(factor(salary_train$occupation,levels = c(level_occ),labels = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14)))
salary_train$relationship <- as.integer(factor(salary_train$relationship,levels = c(level_rel),labels = c(1,2,3,4,5,6)))
salary_train$race <- as.integer(factor(salary_train$race,levels = c(level_race),labels = c(1,2,3,4,5)))
salary_train$sex <- as.integer(factor(salary_train$sex,levels = c(level_sex),labels = c(1,2)))
salary_train$native <- as.integer(factor(salary_train$native,levels = c(level_native),labels = c(seq(1,40,1))))
salary_train$Salary <- as.integer(factor(salary_train$Salary,levels = c(level_salary),labels = c(1,2)))
View(salary_train)
str(salary_train)
table(salary_train$Salary)
summary(salary_train)
plot(salary_train)
boxplot(salary_train)
boxplot(salary_train$educationno)
ggplot(data=salary_train)+geom_bar(mapping = aes(x=salary_train$educationno))
ggplot(data=salary_train)+geom_bar(mapping = aes(x=salary_train$Salary))
#Test data
salary_test<-read.csv("C:/Users/india/Desktop/data science/assignments/svm/SalaryData_Test.csv")
level_work <- levels(salary_test$workclass)
leveledu <- levels(salary_test$education)
level_mari <- levels(salary_test$maritalstatus)
level_occ <- levels(salary_test$occupation)
level_rel <- levels(salary_test$relationship)
level_race <- levels(salary_test$race)
level_sex <- levels(salary_test$sex)
level_native <- levels(salary_test$native)
level_salary <- levels(salary_test$Salary)
salary_test$workclass <- as.integer(factor(salary_test$workclass,levels =c(level_work),labels=c(1,2,3,4,5,6,7)))
salary_test$education <- as.integer(factor(salary_test$education,levels = c(leveledu),labels = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16))) 
salary_test$maritalstatus <- as.integer(factor(salary_test$maritalstatus,levels = c(level_mari),labels =c(1,2,3,4,5,6,7) ))
salary_test$occupation <- as.integer(factor(salary_test$occupation,levels = c(level_occ),labels = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14)))
salary_test$relationship <- as.integer(factor(salary_test$relationship,levels = c(level_rel),labels = c(1,2,3,4,5,6)))
salary_test$race <- as.integer(factor(salary_test$race,levels = c(level_race),labels = c(1,2,3,4,5)))
salary_test$sex <- as.integer(factor(salary_test$sex,levels = c(level_sex),labels = c(1,2)))
salary_test$native <- as.integer(factor(salary_test$native,levels = c(level_native),labels = c(seq(1,40,1))))
salary_test$Salary <- as.integer(factor(salary_test$Salary,levels = c(level_salary),labels = c(1,2)))

View(salary_test)
str(salary_test)
table(salary_test$Salary)
summary(salary_test)
plot(salary_test)
boxplot(salary_test)
boxplot(salary_test$educationno)
ggplot(data=salary_test)+geom_bar(mapping = aes(x=salary_test$educationno))
ggplot(data=salary_test)+geom_bar(mapping = aes(x=salary_test$Salary))

#SVM model
arr<-c("rbfdot","polydot","tanhdot","vanilladot","laplacedot","besseldot","anovadot","splinedot","stringdot")
accuracy<-list()
pred_inf<-list()
table_inf<-list()
for(i in arr){
  model<-ksvm(Salary~.,data=salary_train,arr=i)
  pred<-predict(model,salary_test)
  pred_inf[[i]]<-pred
  accuracy[[i]]<-(cor(pred,salary_test$Salary))
  table_inf<-table(pred,salary_test$Salary)
  
}
accuracy
pred_inf
table_inf
#rbfdot has the highest accuracy hence it is used as the kernel


